steps:

  # View files
  - name: 'bash'
    args: ['ls']
    id: 'View files in base'

  # Create image for Flask on Cloud Run
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', 
            '-t', 'eu.gcr.io/$PROJECT_ID/river-online-ml/vertexai/trainer:v1',
            '-t', 'eu.gcr.io/$PROJECT_ID/river-online-ml/vertexai/trainer:latest',
            '.']

timeout: 5800s
tags: ['latest']
images: [ 'eu.gcr.io/$PROJECT_ID/river-online-ml/vertexai/trainer' ]
